<a href="https://colab.research.google.com/github/sialdyy/Ngoreng/blob/main/SatriaDataParticipant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
# Mengimpor dataset
dataset = pd.read_csv('train_fktp.txt')
dataset

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,50765420,20.064983,958073632,2019-08-01,2019-08-01,61,6108,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat
1,95085112.0,26931775,2.626307,449590620P000054,2020-06-17,2020-06-17,51,5171,9,3,...,K297,"Gastritis, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
2,224470578.0,227368233,1.051830,467490619P000001,2019-06-01,2019-06-01,35,3516,9,2,...,Z309,"Contraceptive management, unspecified",98,9998,98,98,98,98,1,Belum_Sehat
3,63871289.0,62313678,364.741455,254321219Y002368,2019-12-21,2019-12-21,34,3402,3,1,...,I10,Essential (primary) hypertension,98,9998,98,98,98,98,1,Belum_Sehat
4,29915626.0,113446188,1.050523,88681119P000020,2019-11-04,2019-11-04,35,3509,3,1,...,I110,Hypertensive heart disease with (congestive) h...,98,9998,98,98,98,98,1,Belum_Sehat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,91270403,14.246229,1285820875,2020-07-29,2020-07-29,35,3505,9,3,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056894,30859241.0,30859241,3.886934,315641120P000514,2020-11-14,2020-11-14,35,3514,9,2,...,H269,"Cataract, unspecified",35,3514,9,2,14,99,1,Belum_Sehat
4056895,8859416.0,8859416,6.146070,962412926,2019-08-16,2019-08-16,11,1171,4,2,...,9999,9999,98,9998,98,98,98,98,2,Sehat
4056896,399491834.0,399491834,26.548826,273170420P000003,2020-04-01,2020-04-01,74,7402,3,1,...,K30,Dyspepsia,98,9998,98,98,98,98,1,Belum_Sehat
4056897,99146724.0,39321920,88.348953,1188955927,2020-03-14,2020-03-14,73,7317,3,1,...,9999,9999,98,9998,98,98,98,98,2,Sehat

**Dimension**

In [ ]:
dataset.shape

(4056898, 26)

**Variabel Types**

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056898 entries, 0 to 4056897
Data columns (total 26 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   Nomor peserta                                     float64
 1   Nomor keluarga                                    int64
 2   Bobot                                             float64
 3   ID Kunjungan FKTP                                 object
 4   Tanggal datang kunjungan FKTP                     object
 5   Tanggal pulang kunjungan FKTP                     object
 6   Provinsi FKTP                                     int64
 7   Kabupaten/Kota FKTP                               int64
 8   Kepemilikan FKTP                                  int64
 9   Jenis FKTP                                        int64
 10  Tipe FKTP                                         int64
 11  Tingkat Pelayanan FKTP                            int64
 12  Jenis Poli FKTP                                   float64
 13  Segmen Peserta saat akses layanan FKTP            int64
 14  Kode dan nama diagnosis ICD 10 (3 digit)          int64
 15  Kode diagnosis ICD 10 (3 digit)                   object
 16  Kode diagnosis (beragam 3-5 digit)                object
 17  Nama diagnosis berasal dari kode diagnosis FKP15  object
 18  Provinsi faskes tujuan rujukan                    int64
 19  Kabupaten/Kota faskes tujuan rujukan              int64
 20  Kepemilikan faskes tujuan rujukan                 int64
 21  Jenis faskes tujuan rujukan                       int64
 22  Tipe faskes tujuan rujukan                        int64
 23  Poli faskes tujuan rujukan                        int64
 24  Jenis Kunjungan FKTP                              int64
 25  Kelas Status Pulang Peserta                       object
dtypes: float64(3), int64(16), object(7)
memory usage: 804.7+ MB

**Descriptive Statistics**

In [ ]:
dataset.describe(include='all')

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
count,4.056898e+06,4.056898e+06,4.056898e+06,4056898,4056898,4056898,4.056898e+06,4.056898e+06,4.056898e+06,4.056898e+06,...,4056898,4056898,4.056898e+06,4.056898e+06,4.056898e+06,4.056898e+06,4.056898e+06,4.056898e+06,4.056898e+06,4056898
unique,NaN,NaN,NaN,4056898,731,736,NaN,NaN,NaN,NaN,...,9665,9660,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
top,NaN,NaN,NaN,958073632,2020-02-10,2020-02-10,NaN,NaN,NaN,NaN,...,9999,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Belum_Sehat
freq,NaN,NaN,NaN,1,10175,10180,NaN,NaN,NaN,NaN,...,1380241,1380241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2634511
mean,9.153457e+07,9.488335e+07,1.056512e+02,NaN,NaN,NaN,3.608867e+01,3.636691e+03,5.652855e+00,1.677882e+00,...,NaN,NaN,9.223593e+01,9.406489e+03,8.944209e+01,8.893204e+01,9.169130e+01,9.809351e+01,1.340221e+00,NaN
std,8.994426e+07,8.852257e+07,1.886474e+02,NaN,NaN,NaN,1.870093e+01,1.869268e+03,2.935862e+00,8.353439e-01,...,NaN,NaN,1.877501e+01,1.922342e+03,2.665995e+01,2.823298e+01,1.973518e+01,2.911491e-01,4.737833e-01,NaN
min,1.500000e+01,1.500000e+01,5.106980e-01,NaN,NaN,NaN,1.100000e+01,1.101000e+03,1.000000e+00,1.000000e+00,...,NaN,NaN,1.100000e+01,1.101000e+03,1.000000e+00,1.000000e+00,5.000000e+00,9.800000e+01,1.000000e+00,NaN
25%,3.377226e+07,3.577565e+07,1.676808e+01,NaN,NaN,NaN,3.100000e+01,3.171000e+03,3.000000e+00,1.000000e+00,...,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.000000e+00,NaN
50%,6.760764e+07,7.181594e+07,5.147561e+01,NaN,NaN,NaN,3.300000e+01,3.318000e+03,3.000000e+00,1.000000e+00,...,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.000000e+00,NaN
75%,1.015584e+08,1.113200e+08,1.282688e+02,NaN,NaN,NaN,3.600000e+01,3.603000e+03,9.000000e+00,2.000000e+00,...,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,2.000000e+00,NaN
max,4.553885e+08,4.553824e+08,3.035342e+04,NaN,NaN,NaN,9.400000e+01,9.471000e+03,9.000000e+00,7.000000e+00,...,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.900000e+01,9.900000e+01,2.000000e+00,NaN

**Missing Data dan Cara Mengatasi**

In [ ]:
#Missing Data
dataset.isnull().sum()

Nomor peserta                                             0
Nomor keluarga                                            0
Bobot                                                     0
ID Kunjungan FKTP                                         0
Tanggal datang kunjungan FKTP                             0
Tanggal pulang kunjungan FKTP                             0
Provinsi FKTP                                             0
Kabupaten/Kota FKTP                                       0
Kepemilikan FKTP                                          0
Jenis FKTP                                                0
Tipe FKTP                                                 0
Tingkat Pelayanan FKTP                                    0
Jenis Poli FKTP                                           1
Segmen Peserta saat akses layanan FKTP                    0
Kode dan nama diagnosis ICD 10 (3 digit)                  0
Kode diagnosis ICD 10 (3 digit)                     1380241
Kode diagnosis (beragam 3-5 digit)                        0
Nama diagnosis berasal dari kode diagnosis FKP15          0
Provinsi faskes tujuan rujukan                            0
Kabupaten/Kota faskes tujuan rujukan                      0
Kepemilikan faskes tujuan rujukan                         0
Jenis faskes tujuan rujukan                               0
Tipe faskes tujuan rujukan                                0
Poli faskes tujuan rujukan                                0
Jenis Kunjungan FKTP                                      0
Kelas Status Pulang Peserta                               0
dtype: int64

In [ ]:
modus = dataset['Jenis Poli FKTP'].mode
dataset['Jenis Poli FKTP'] = dataset['Jenis Poli FKTP'].fillna(modus)
dataset.isnull().sum()

Nomor peserta                                             0
Nomor keluarga                                            0
Bobot                                                     0
ID Kunjungan FKTP                                         0
Tanggal datang kunjungan FKTP                             0
Tanggal pulang kunjungan FKTP                             0
Provinsi FKTP                                             0
Kabupaten/Kota FKTP                                       0
Kepemilikan FKTP                                          0
Jenis FKTP                                                0
Tipe FKTP                                                 0
Tingkat Pelayanan FKTP                                    0
Jenis Poli FKTP                                           0
Segmen Peserta saat akses layanan FKTP                    0
Kode dan nama diagnosis ICD 10 (3 digit)                  0
Kode diagnosis ICD 10 (3 digit)                     1380241
Kode diagnosis (beragam 3-5 digit)                        0
Nama diagnosis berasal dari kode diagnosis FKP15          0
Provinsi faskes tujuan rujukan                            0
Kabupaten/Kota faskes tujuan rujukan                      0
Kepemilikan faskes tujuan rujukan                         0
Jenis faskes tujuan rujukan                               0
Tipe faskes tujuan rujukan                                0
Poli faskes tujuan rujukan                                0
Jenis Kunjungan FKTP                                      0
Kelas Status Pulang Peserta                               0
dtype: int64

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056898 entries, 0 to 4056897
Data columns (total 26 columns):
 #   Column                                            Dtype
---  ------                                            -----
 0   Nomor peserta                                     float64
 1   Nomor keluarga                                    int64
 2   Bobot                                             float64
 3   ID Kunjungan FKTP                                 object
 4   Tanggal datang kunjungan FKTP                     object
 5   Tanggal pulang kunjungan FKTP                     object
 6   Provinsi FKTP                                     int64
 7   Kabupaten/Kota FKTP                               int64
 8   Kepemilikan FKTP                                  int64
 9   Jenis FKTP                                        int64
 10  Tipe FKTP                                         int64
 11  Tingkat Pelayanan FKTP                            int64
 12  Jenis Poli FKTP                                   object
 13  Segmen Peserta saat akses layanan FKTP            int64
 14  Kode dan nama diagnosis ICD 10 (3 digit)          int64
 15  Kode diagnosis ICD 10 (3 digit)                   object
 16  Kode diagnosis (beragam 3-5 digit)                object
 17  Nama diagnosis berasal dari kode diagnosis FKP15  object
 18  Provinsi faskes tujuan rujukan                    int64
 19  Kabupaten/Kota faskes tujuan rujukan              int64
 20  Kepemilikan faskes tujuan rujukan                 int64
 21  Jenis faskes tujuan rujukan                       int64
 22  Tipe faskes tujuan rujukan                        int64
 23  Poli faskes tujuan rujukan                        int64
 24  Jenis Kunjungan FKTP                              int64
 25  Kelas Status Pulang Peserta                       object
dtypes: float64(2), int64(16), object(8)
memory usage: 804.7+ MB

In [ ]:
dataset1 = dataset.drop(dataset.columns[[3,4,5,12,15,16,17]], axis = 1)
dataset1

,Nomor peserta,Nomor keluarga,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP,Kelas Status Pulang Peserta
0,157978748.0,50765420,20.064983,61,6108,3,1,4,1,2,9999,98,9998,98,98,98,98,2,Sehat
1,95085112.0,26931775,2.626307,51,5171,9,3,2,1,4,773,98,9998,98,98,98,98,1,Belum_Sehat
2,224470578.0,227368233,1.051830,35,3516,9,2,1,1,4,1757,98,9998,98,98,98,98,1,Belum_Sehat
3,63871289.0,62313678,364.741455,34,3402,3,1,4,1,5,621,98,9998,98,98,98,98,1,Belum_Sehat
4,29915626.0,113446188,1.050523,35,3509,3,1,4,1,1,622,98,9998,98,98,98,98,1,Belum_Sehat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,91270403,14.246229,35,3505,9,3,2,1,4,9999,98,9998,98,98,98,98,2,Sehat
4056894,30859241.0,30859241,3.886934,35,3514,9,2,1,1,5,561,35,3514,9,2,14,99,1,Belum_Sehat
4056895,8859416.0,8859416,6.146070,11,1171,4,2,1,1,5,9999,98,9998,98,98,98,98,2,Sehat
4056896,399491834.0,399491834,26.548826,74,7402,3,1,3,1,2,774,98,9998,98,98,98,98,1,Belum_Sehat
4056897,99146724.0,39321920,88.348953,73,7317,3,1,4,1,2,9999,98,9998,98,98,98,98,2,Sehat

In [ ]:
dataset1['Kelas Status Pulang Peserta'].replace(['Belum_Sehat', 'Sehat'],
                        [0, 1], inplace=True)

In [ ]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056898 entries, 0 to 4056897
Data columns (total 19 columns):
 #   Column                                    Dtype
---  ------                                    -----
 0   Nomor peserta                             float64
 1   Nomor keluarga                            int64
 2   Bobot                                     float64
 3   Provinsi FKTP                             int64
 4   Kabupaten/Kota FKTP                       int64
 5   Kepemilikan FKTP                          int64
 6   Jenis FKTP                                int64
 7   Tipe FKTP                                 int64
 8   Tingkat Pelayanan FKTP                    int64
 9   Segmen Peserta saat akses layanan FKTP    int64
 10  Kode dan nama diagnosis ICD 10 (3 digit)  int64
 11  Provinsi faskes tujuan rujukan            int64
 12  Kabupaten/Kota faskes tujuan rujukan      int64
 13  Kepemilikan faskes tujuan rujukan         int64
 14  Jenis faskes tujuan rujukan               int64
 15  Tipe faskes tujuan rujukan                int64
 16  Poli faskes tujuan rujukan                int64
 17  Jenis Kunjungan FKTP                      int64
 18  Kelas Status Pulang Peserta               int64
dtypes: float64(2), int64(17)
memory usage: 588.1 MB

In [ ]:
dataset1.isnull().sum()

Nomor peserta                               0
Nomor keluarga                              0
Bobot                                       0
Provinsi FKTP                               0
Kabupaten/Kota FKTP                         0
Kepemilikan FKTP                            0
Jenis FKTP                                  0
Tipe FKTP                                   0
Tingkat Pelayanan FKTP                      0
Segmen Peserta saat akses layanan FKTP      0
Kode dan nama diagnosis ICD 10 (3 digit)    0
Provinsi faskes tujuan rujukan              0
Kabupaten/Kota faskes tujuan rujukan        0
Kepemilikan faskes tujuan rujukan           0
Jenis faskes tujuan rujukan                 0
Tipe faskes tujuan rujukan                  0
Poli faskes tujuan rujukan                  0
Jenis Kunjungan FKTP                        0
Kelas Status Pulang Peserta                 0
dtype: int64

In [ ]:
X = dataset1.iloc[:,0:18]
y = dataset1.iloc[:, 18]

In [ ]:
X

,Nomor peserta,Nomor keluarga,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
0,157978748.0,50765420,20.064983,61,6108,3,1,4,1,2,9999,98,9998,98,98,98,98,2
1,95085112.0,26931775,2.626307,51,5171,9,3,2,1,4,773,98,9998,98,98,98,98,1
2,224470578.0,227368233,1.051830,35,3516,9,2,1,1,4,1757,98,9998,98,98,98,98,1
3,63871289.0,62313678,364.741455,34,3402,3,1,4,1,5,621,98,9998,98,98,98,98,1
4,29915626.0,113446188,1.050523,35,3509,3,1,4,1,1,622,98,9998,98,98,98,98,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4056893,212666736.0,91270403,14.246229,35,3505,9,3,2,1,4,9999,98,9998,98,98,98,98,2
4056894,30859241.0,30859241,3.886934,35,3514,9,2,1,1,5,561,35,3514,9,2,14,99,1
4056895,8859416.0,8859416,6.146070,11,1171,4,2,1,1,5,9999,98,9998,98,98,98,98,2
4056896,399491834.0,399491834,26.548826,74,7402,3,1,3,1,2,774,98,9998,98,98,98,98,1
4056897,99146724.0,39321920,88.348953,73,7317,3,1,4,1,2,9999,98,9998,98,98,98,98,2

In [ ]:
y

0          1
1          0
2          0
3          0
4          0
          ..
4056893    1
4056894    0
4056895    1
4056896    0
4056897    1
Name: Kelas Status Pulang Peserta, Length: 4056898, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_clf = XGBClassifier()

In [ ]:
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [ ]:
xgb_clf

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [ ]:
y_pred=xgb_clf.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.9968135147438166

In [ ]:
# Membuat confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[790639,    243],
       [  2466, 423722]], dtype=int64)

**DATA TESTING**

In [ ]:
# Mengimpor dataset
datatest = pd.read_csv('test_fktp.txt')
datatest

C:\Users\user\AppData\Local\Temp\ipykernel_24308\1396928172.py:2: DtypeWarning: Columns (3,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  datatest = pd.read_csv('test_fktp.txt')

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis ICD 10 (3 digit),Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
0,187883292.0,98048784,240.884842,954386050,2019-08-21,2019-08-21,31,3172,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
1,123307139.0,20969999,47.378571,774246805,2019-02-12,2019-02-12,17,1705,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
2,21416273.0,21416273,5.882927,1202010273,2020-03-27,2020-03-27,64,6402,3,1,...,NaN,9999,9999,98,9998,98,98,98,98,2
3,97630052.0,97630052,172.916031,1286640248,2020-07-30,2020-07-30,18,1872,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
4,124531163.0,124531163,187.203140,1285179242,2020-07-28,2020-07-28,18,1809,9,2,...,NaN,9999,9999,98,9998,98,98,98,98,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014220,51801010.0,51801010,7.563763,248870919P000406,2019-09-08,2019-09-08,36,3601,9,2,...,Z99,Z992,Dependence on renal dialysis,36,3602,3,1,27,99,1
1014221,339397889.0,339397889,11.063568,116000620P000034,2020-06-02,2020-06-02,33,3373,9,2,...,Z99,Z999,Dependence on unspecified enabling machine and...,98,9998,98,98,98,98,1
1014222,76213152.0,76213152,286.792694,160421019P000631,2019-10-15,2019-10-15,32,3276,3,1,...,Z99,Z992,Dependence on renal dialysis,32,3276,9,1,33,99,1
1014223,101797983.0,101797983,30.222155,332670919P000083,2019-09-06,2019-09-06,16,1606,3,1,...,Z99,Z992,Dependence on renal dialysis,16,1606,3,1,27,99,1
1014224,20239553.0,20239553,233.636230,106050119Y000587,2019-01-30,2019-01-30,19,1904,3,1,...,Z99,Z992,Dependence on renal dialysis,19,1971,3,1,28,99,1

In [ ]:
datatest.shape

(1014225, 25)

In [ ]:
datatest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014225 entries, 0 to 1014224
Data columns (total 25 columns):
 #   Column                                            Non-Null Count    Dtype
---  ------                                            --------------    -----
 0   Nomor peserta                                     1014225 non-null  float64
 1   Nomor keluarga                                    1014225 non-null  int64
 2   Bobot                                             1014225 non-null  float64
 3   ID Kunjungan FKTP                                 1014225 non-null  object
 4   Tanggal datang kunjungan FKTP                     1014225 non-null  object
 5   Tanggal pulang kunjungan FKTP                     1014225 non-null  object
 6   Provinsi FKTP                                     1014225 non-null  int64
 7   Kabupaten/Kota FKTP                               1014225 non-null  int64
 8   Kepemilikan FKTP                                  1014225 non-null  int64
 9   Jenis FKTP                                        1014225 non-null  int64
 10  Tipe FKTP                                         1014225 non-null  int64
 11  Tingkat Pelayanan FKTP                            1014225 non-null  int64
 12  Jenis Poli FKTP                                   1014225 non-null  int64
 13  Segmen Peserta saat akses layanan FKTP            1014225 non-null  int64
 14  Kode dan nama diagnosis ICD 10 (3 digit)          1014225 non-null  int64
 15  Kode diagnosis ICD 10 (3 digit)                   668313 non-null   object
 16  Kode diagnosis (beragam 3-5 digit)                1014225 non-null  object
 17  Nama diagnosis berasal dari kode diagnosis FKP15  1014225 non-null  object
 18  Provinsi faskes tujuan rujukan                    1014225 non-null  int64
 19  Kabupaten/Kota faskes tujuan rujukan              1014225 non-null  int64
 20  Kepemilikan faskes tujuan rujukan                 1014225 non-null  int64
 21  Jenis faskes tujuan rujukan                       1014225 non-null  int64
 22  Tipe faskes tujuan rujukan                        1014225 non-null  int64
 23  Poli faskes tujuan rujukan                        1014225 non-null  int64
 24  Jenis Kunjungan FKTP                              1014225 non-null  int64
dtypes: float64(2), int64(17), object(6)
memory usage: 193.4+ MB

In [ ]:
datatest.describe(include='all')

,Nomor peserta,Nomor keluarga,Bobot,ID Kunjungan FKTP,Tanggal datang kunjungan FKTP,Tanggal pulang kunjungan FKTP,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,...,Kode diagnosis ICD 10 (3 digit),Kode diagnosis (beragam 3-5 digit),Nama diagnosis berasal dari kode diagnosis FKP15,Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
count,1.014225e+06,1.014225e+06,1.014225e+06,1014225.0,1014225,1014225,1.014225e+06,1.014225e+06,1.014225e+06,1.014225e+06,...,668313,1014225.0,1014225.0,1.014225e+06,1.014225e+06,1.014225e+06,1.014225e+06,1.014225e+06,1.014225e+06,1.014225e+06
unique,NaN,NaN,NaN,1014225.0,731,735,NaN,NaN,NaN,NaN,...,1662,6837.0,6834.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,954386050.0,2020-02-10,2020-02-10,NaN,NaN,NaN,NaN,...,J06,9999.0,9999.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,1.0,2570,2563,NaN,NaN,NaN,NaN,...,59919,327680.0,327680.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,9.159896e+07,9.492149e+07,1.056841e+02,NaN,NaN,NaN,3.609869e+01,3.637708e+03,5.651684e+00,1.677975e+00,...,NaN,NaN,NaN,9.225917e+01,9.408837e+03,8.946482e+01,8.895451e+01,9.170838e+01,9.809328e+01,1.341060e+00
std,8.995272e+07,8.858823e+07,1.873387e+02,NaN,NaN,NaN,1.871773e+01,1.870930e+03,2.935942e+00,8.368108e-01,...,NaN,NaN,NaN,1.873706e+01,1.918504e+03,2.662540e+01,2.820152e+01,1.970859e+01,2.908261e-01,4.740658e-01
min,1.500000e+01,1.500000e+01,5.106980e-01,NaN,NaN,NaN,1.100000e+01,1.101000e+03,1.000000e+00,1.000000e+00,...,NaN,NaN,NaN,1.100000e+01,1.101000e+03,1.000000e+00,1.000000e+00,5.000000e+00,9.800000e+01,1.000000e+00
25%,3.382176e+07,3.580259e+07,1.680836e+01,NaN,NaN,NaN,3.100000e+01,3.171000e+03,3.000000e+00,1.000000e+00,...,NaN,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.000000e+00
50%,6.769082e+07,7.177364e+07,5.158066e+01,NaN,NaN,NaN,3.300000e+01,3.318000e+03,3.000000e+00,1.000000e+00,...,NaN,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,1.000000e+00
75%,1.016452e+08,1.112675e+08,1.281638e+02,NaN,NaN,NaN,3.600000e+01,3.603000e+03,9.000000e+00,2.000000e+00,...,NaN,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.800000e+01,9.800000e+01,2.000000e+00
max,4.553771e+08,4.553795e+08,3.710185e+04,NaN,NaN,NaN,9.400000e+01,9.471000e+03,9.000000e+00,7.000000e+00,...,NaN,NaN,NaN,9.800000e+01,9.998000e+03,9.800000e+01,9.800000e+01,9.900000e+01,9.900000e+01,2.000000e+00

In [ ]:
datatest1 = datatest.drop(datatest.columns[[3,4,5,12,15,16,17]], axis = 1)
datatest1

,Nomor peserta,Nomor keluarga,Bobot,Provinsi FKTP,Kabupaten/Kota FKTP,Kepemilikan FKTP,Jenis FKTP,Tipe FKTP,Tingkat Pelayanan FKTP,Segmen Peserta saat akses layanan FKTP,Kode dan nama diagnosis ICD 10 (3 digit),Provinsi faskes tujuan rujukan,Kabupaten/Kota faskes tujuan rujukan,Kepemilikan faskes tujuan rujukan,Jenis faskes tujuan rujukan,Tipe faskes tujuan rujukan,Poli faskes tujuan rujukan,Jenis Kunjungan FKTP
0,187883292.0,98048784,240.884842,31,3172,9,2,1,1,5,9999,98,9998,98,98,98,98,2
1,123307139.0,20969999,47.378571,17,1705,3,1,3,1,2,9999,98,9998,98,98,98,98,2
2,21416273.0,21416273,5.882927,64,6402,3,1,4,1,2,9999,98,9998,98,98,98,98,2
3,97630052.0,97630052,172.916031,18,1872,9,2,5,1,5,9999,98,9998,98,98,98,98,2
4,124531163.0,124531163,187.203140,18,1809,9,2,5,1,2,9999,98,9998,98,98,98,98,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014220,51801010.0,51801010,7.563763,36,3601,9,2,1,1,4,1818,36,3602,3,1,27,99,1
1014221,339397889.0,339397889,11.063568,33,3373,9,2,1,1,4,1818,98,9998,98,98,98,98,1
1014222,76213152.0,76213152,286.792694,32,3276,3,1,3,1,5,1818,32,3276,9,1,33,99,1
1014223,101797983.0,101797983,30.222155,16,1606,3,1,3,1,4,1818,16,1606,3,1,27,99,1
1014224,20239553.0,20239553,233.636230,19,1904,3,1,3,1,2,1818,19,1971,3,1,28,99,1

In [ ]:
datatest1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014225 entries, 0 to 1014224
Data columns (total 18 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Nomor peserta                             1014225 non-null  float64
 1   Nomor keluarga                            1014225 non-null  int64
 2   Bobot                                     1014225 non-null  float64
 3   Provinsi FKTP                             1014225 non-null  int64
 4   Kabupaten/Kota FKTP                       1014225 non-null  int64
 5   Kepemilikan FKTP                          1014225 non-null  int64
 6   Jenis FKTP                                1014225 non-null  int64
 7   Tipe FKTP                                 1014225 non-null  int64
 8   Tingkat Pelayanan FKTP                    1014225 non-null  int64
 9   Segmen Peserta saat akses layanan FKTP    1014225 non-null  int64
 10  Kode dan nama diagnosis ICD 10 (3 digit)  1014225 non-null  int64
 11  Provinsi faskes tujuan rujukan            1014225 non-null  int64
 12  Kabupaten/Kota faskes tujuan rujukan      1014225 non-null  int64
 13  Kepemilikan faskes tujuan rujukan         1014225 non-null  int64
 14  Jenis faskes tujuan rujukan               1014225 non-null  int64
 15  Tipe faskes tujuan rujukan                1014225 non-null  int64
 16  Poli faskes tujuan rujukan                1014225 non-null  int64
 17  Jenis Kunjungan FKTP                      1014225 non-null  int64
dtypes: float64(2), int64(16)
memory usage: 139.3 MB

In [ ]:
X_test = datatest1.iloc[:,0:18]

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014225 entries, 0 to 1014224
Data columns (total 18 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   Nomor peserta                             1014225 non-null  float64
 1   Nomor keluarga                            1014225 non-null  int64
 2   Bobot                                     1014225 non-null  float64
 3   Provinsi FKTP                             1014225 non-null  int64
 4   Kabupaten/Kota FKTP                       1014225 non-null  int64
 5   Kepemilikan FKTP                          1014225 non-null  int64
 6   Jenis FKTP                                1014225 non-null  int64
 7   Tipe FKTP                                 1014225 non-null  int64
 8   Tingkat Pelayanan FKTP                    1014225 non-null  int64
 9   Segmen Peserta saat akses layanan FKTP    1014225 non-null  int64
 10  Kode dan nama diagnosis ICD 10 (3 digit)  1014225 non-null  int64
 11  Provinsi faskes tujuan rujukan            1014225 non-null  int64
 12  Kabupaten/Kota faskes tujuan rujukan      1014225 non-null  int64
 13  Kepemilikan faskes tujuan rujukan         1014225 non-null  int64
 14  Jenis faskes tujuan rujukan               1014225 non-null  int64
 15  Tipe faskes tujuan rujukan                1014225 non-null  int64
 16  Poli faskes tujuan rujukan                1014225 non-null  int64
 17  Jenis Kunjungan FKTP                      1014225 non-null  int64
dtypes: float64(2), int64(16)
memory usage: 139.3 MB

In [ ]:
# predict the results
y_predtest=xgb_clf.predict(X_test)

In [ ]:
import numpy as np
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)

0.9968135147438166

In [ ]:
# Membuat confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[790639,    243],
       [  2466, 423722]], dtype=int64)

In [ ]:
submission=pd.read_csv('submission.csv')
submission

C:\Users\user\AppData\Local\Temp\ipykernel_24308\1356218435.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  submission=pd.read_csv('submission.csv')

         Unnamed: 0             FKP02  Status
0                 1         954386050     NaN
1                 2         774246805     NaN
2                 3        1202010273     NaN
3                 4        1286640248     NaN
4                 5        1285179242     NaN
...             ...               ...     ...
1014220     1014221  248870919P000406     NaN
1014221     1014222  116000620P000034     NaN
1014222     1014223  160421019P000631     NaN
1014223     1014224  332670919P000083     NaN
1014224     1014225  106050119Y000587     NaN

[1014225 rows x 3 columns]

In [ ]:
submission['Status']=y_predtest
submission

         Unnamed: 0             FKP02  Status
0                 1         954386050       1
1                 2         774246805       1
2                 3        1202010273       1
3                 4        1286640248       1
4                 5        1285179242       1
...             ...               ...     ...
1014220     1014221  248870919P000406       0
1014221     1014222  116000620P000034       0
1014222     1014223  160421019P000631       0
1014223     1014224  332670919P000083       0
1014224     1014225  106050119Y000587       0

[1014225 rows x 3 columns]

In [ ]:
submission['Unnamed: 0'] = submission['Unnamed: 0'].astype(str)
submission['FKP02'] = submission['FKP02'].astype(str)

In [ ]:
import csv
submission.to_csv('submission.csv', index=False, quoting=csv.QUOTE_NONNUMERIC)